### ISSUE TITLE
Clause set parsing does not accept alphanumerical characters

### ISSUE THREAD

**Issue by JuliusHenke** [rec0de/kalkulierbar#1]
Reproduce:
https://kbar.app/prop-tableaux
Clause set: a1,a2

Maybe support DIMACS CNF format?
https://www.reddit.com/r/logic/comments/htpgtj/kalkulierbar_a_webapp_for_doing_logic_calculi/fyl02ls

**Comment by rec0de** [comment]
Fixed in #3
